### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nidhidhamnani** [kresnajenie/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [] All relevant URLs written as markdown links
Please add some hyperlinks

- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar

- [] Lab report is on its own page, not the index page
Your main page is awesome, please also add a section for Lab Reports on main page and link it to lab-report-1-week-2 page

- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Loved the main page. Great job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by kresnajenie** [comment]
I've updated the website to have a link to the report page and a hyperlink on the report page.

**Comment by nidhidhamnani** [comment]
Great job!
